language: python


python:
  - "2.7"
  - "3.4"
#  - "nightly"


# Command to install dependencies
install:
  - "pip install unittest2"
#  - "pip install -r requirements.txt"


# Command to run tests (next time I'll go with Nosetest)
script: python test-suite.py


# Branches Whitelist, any other branch is ignored
branches:
  only:
    - master
    - develop 
    - /^feature-.*$/
    - /^hotfix-.*$/
    - /^release-.*$/

